name: BibleRead
description: Bible Reading Tracking App
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    flutter_cupertino_localizations: ^1.0.1
    bloc: ^3.0.0
    percent_indicator: ^2.1.1+1
    flutter_svg: ^0.15.0
    flutter_slidable: ^0.5.4
    line_icons: ^0.2.0
    flutter_icons: ^1.0.0+1 
    flutter_bloc: ^3.2.0
    line_awesome_icons: ^1.0.4+2
    line_awesome_flutter: ^1.0.1
    wave: ^0.0.8
    provider: ^4.0.3
    path_provider: ^1.5.1
    simple_animations: ^1.3.6
    flutter_swiper: ^1.1.6
    flutter_html: ^0.11.1
    flutter_widget_from_html: ^0.3.2+1
    flutter_widget_from_html_core: ^0.3.2+1
    cupertino_icons: ^0.1.2
    provider_architecture: ^1.0.3
    responsive_builder: ^0.1.4
    logger: ^0.7.0+2
    get_it: ^3.0.3
    equatable: ^1.1.0
    flutter_cupertino_data_picker: ^0.8.6
    flutter_cupertino_date_picker: ^1.0.12
    shared_preferences: ^0.5.6+1
    flutter_device_locale: ^0.3.4+1
    better_uuid: ^0.1.2
    intl: ^0.16.0
    sqflite: ^1.2.0
    shimmer: ^1.0.1
    connectivity: ^0.4.8+1
    xlive_switch: ^1.0.5
    extended_text: ^0.7.1
    on_boarding_ui: ^0.0.4
    share: ^0.6.3+6 

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/BibleRead.db
        - assets/json/
    fonts:
    - family: BibleReadIcons
      fonts:
        - asset: assets/fonts/BibleIcon.ttf
    - family: Avenir Next
      fonts:
        - asset: assets/fonts/AvenirNext-Regular.ttf
          style: normal
        - asset: assets/fonts/AvenirNext-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/AvenirNext-Medium.ttf
          weight: 300
        - asset: assets/fonts/AvenirNext-DemiBold.ttf
          weight: 400
        - asset: assets/fonts/AvenirNext-Bold.ttf
          weight: 700
        - asset: assets/fonts/AvenirNext-Heavy.ttf
          weight: 900
    - family: Lao MN
      fonts:
        - asset: assets/fonts/LaoMN.ttf
          style: normal
        - asset: assets/fonts/LaoMN-Bold.ttf
          weight: 700
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf
          style: normal
        - asset: assets/fonts/PTSerif-Bold.ttf
          weight: 600
        - asset: assets/fonts/PTSerif-Italic.ttf
          style: italic

